{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Leistung/Batterie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batterie: Füllstand",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "senec.bat.fuel" }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "senec.power.pv" }
   ]
  },
  {
   "title": "Haus",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "senec.power.house" }
   ]
  },
  {
   "title": "Netz",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "senec.power.grid" }
   ]
  },
  {
   "title": "Batterie: Strom / Füllstand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "target": "constantLine(0)" },
    {
     "target": "alias(senec.bat.current, 'Ladestrom')"
    },
    {
     "target": "alias(senec.bat.fuel, 'Füllstand')"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${pLaden}/${count}  * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    },
    {
     "expression": "${pEntladen}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${p}/$count * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Haus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${p}/$count * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${pOut}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    },
    {
     "expression": "${pIn}/${count} * ((${__to:date:seconds}-${__from:date:seconds})/3600)",
     "reducer": "sum",
     "type": "math"
    }
   ]
  },
  {
   "title": "Leistungen",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(scale(senec.power.bat, -1), 'Batterie (neg=Laden, pos=Entladen)')"
    },
    {
     "target": "alias(senec.power.grid, 'Netz (neg=Einspeisung, pos=Bezug)')"
    },
    {
     "target": "alias(senec.power.house, 'Hausbedarf')"
    },
    {
     "target": "alias(senec.power.pv, 'PV Anlage')"
    }
   ]
  },
  {
   "title": "Batterie: Temperatur / Spannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "alias(senec.bat.voltage, 'Spannung')"
    },
    {
     "target": "alias(senec.bat1.temp1, 'Temperatur 1')"
    },
    {
     "target": "alias(senec.bat1.temp2, 'Temperatur 2')"
    }
   ]
  },
  { "title": "Wechselrichter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Enfluri: Leistung",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(senec.converter1.power_total, 'Total')"
    },
    {
     "target": "alias(senec.converter1.L1.power, 'L1 - HV (West)+Akku')"
    },
    {
     "target": "alias(senec.converter1.L2.power, 'L2 - LV (Ost + West)')"
    },
    {
     "target": "alias(senec.converter1.L3.power, 'L3')"
    }
   ]
  },
  {
   "title": "Enfluri: Spannung",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "target": "alias(senec.converter1.L1.voltage, 'L1 - HV (West)')"
    },
    {
     "target": "alias(senec.converter1.L2.voltage, 'L2 - LV (Ost + West)')"
    },
    {
     "target": "alias(senec.converter1.L3.voltage, 'L3')"
    }
   ]
  },
  {
   "title": "Enfluri: Strom",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "target": "alias(senec.converter1.L1.current, 'L1 - HV (West)')"
    },
    {
     "target": "alias(senec.converter1.L2.current, 'L2 - LV (Ost + West)')"
    },
    {
     "target": "alias(senec.converter1.L3.current, 'L3')"
    }
   ]
  },
  { "title": "PV MPP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "MPP: Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "alias(senec.mpp1.power, 'String 1 - HV (West)')"
    },
    {
     "target": "alias(senec.mpp2.power, 'String 2 - LV (Ost)')"
    },
    {
     "target": "alias(senec.mpp3.power, 'String 3 - LV (West)')"
    }
   ]
  },
  {
   "title": "MPP: Spannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "target": "alias(senec.mpp1.voltage, 'String 1 - HV (West)')"
    },
    {
     "target": "alias(senec.mpp2.voltage, 'String 2 - LV (Ost)')"
    },
    {
     "target": "alias(senec.mpp3.voltage, 'String 3 - LV (West)')"
    }
   ]
  },
  {
   "title": "MPP: Strom",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "target": "alias(senec.mpp1.current, 'String 1 - HV (West)')"
    },
    {
     "target": "alias(senec.mpp2.current, 'String 2 - LV (Ost)')"
    },
    {
     "target": "alias(senec.mpp3.current, 'String 3 - LV (West)')"
    }
   ]
  }
 ]
}